import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/core/layout/navbar";
import { AppProvider } from "@/core/providers/app-provider";
import { MarginBottomBottomBar } from "@/core/components/ui/margin-bottom-bottom-bar";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Overgive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased`}>
        <AppProvider>
          <Navbar />
          {children}
          <MarginBottomBottomBar />
        </AppProvider>
      </body>
    </html>
  );
}
